@startuml User-AMDAX-context
 
' !include ../C4-PlantUML/C4_Context.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!define ICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/
 
!include ICONS/font-awesome-5/users.puml
!include ICONS/font-awesome-5/user_tie.puml
!include ICONS/material/contact_phone.puml
 
' LAYOUT_AS_SKETCH()
' LAYOUT_LEFT_RIGHT()
LAYOUT_WITH_LEGEND()
 
Person_Ext(user, "Clients", "Users who are using AMDAX service. The user can have individual account ar AMDAX or can belong to a legal entity", "users")

Boundary(new, "Customer self-service using AMDAX"){

  System(amdax, "AMDAX System", "Providing AMDAX services to Users.")

  Boundary(az, "External services"){
    System_Ext(b2c, "AZ B2C", "Do Authentication for AMDAX Users.")
    System_Ext(coinroutes, "CoinRoutes", "Crypto-Currencies service provider. AMDAX uses CoinRoutes to work with Counter Parties")
    ' System_Ext(cc, "Contact Center", "Contact point, switches customer calls.")
    ' Person_Ext(counselor, "Customer counselors", "Interacts with customers to handle complaints, process orders, and provide information about OOO service.", "contact_phone")
     
    ' Rel(user, cc, "Makes a call")
    ' Rel(cc, counselor, "Connects and forwards a call to")
    ' Rel(cc, b2c, "Connects and forwards a call to")
    Rel_D(amdax, b2c, "Get Auth Info")
    Rel_D(amdax, coinroutes, "Place Orders")
  }
  
  Rel_R(user, amdax, "Authen/Author")
  Rel_R(user, amdax, "View Balances")
  Rel_R(user, amdax, "Deposit/Withdrawal")
  Rel_R(user, amdax, "Transfers/Payment")
  Rel_R(user, amdax, "Crypto Trading")
}
 
' Person_Ext(manager, "Manager", "Makes a decision from statistics provided by CLOVA AiCall", "user_tie")
' Rel(manager, amdax, "Retrives statistics from")


@enduml